services:
  - type: web
    name: autocarehub-carservice
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_TYPE
        value: sqlite
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.12.0
